Python 3.14.0 (tags/v3.14.0:ebf955d, Oct  7 2025, 10:15:03) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> 
==================== RESTART: C:/Users/JET/Desktop/DLHI 1.PY ===================
your Computer Name: DESKTOP-SHB98US
your IP address: 192.168.1.187
>>> 
==================== RESTART: C:/Users/JET/Desktop/DNS 2.PY ====================
Enter domain name:www.google.com
IP Address of www.google.com is 142.251.221.196
